### PR TITLE
Some additions for pop bumber and Cobra pin physical setup

### PR DESCRIPTION
**Pull request by worldpeace-germany**

### CODE REVIEW

**Comment by cobra18t** [comment]
I would move the Test Rig section toward the end. Just before the Example config.

**Comment by cobra18t** [comment]
Fair enough. I was making a suggestion on what "I would" do if it were my pull request. It is not my pull request, so I am suggesting that you make the changes. You do not need to open a new pull request, just commit changes into your "worldpeace-germany:dev" branch and the new commits will automatically be added to this request. Thanks for your efforts to improve the documentation!

**Comment by worldpeace-germany** [comment]
change done, thanks for the clarifications.

**Comment by cobra18t** [comment]
I am going to merge this and then I have some changes and clarifications to make based on some questions I have been getting.

**Pull request merged**
