### PR TITLE
add initial CobraPin info

### PR DESCRIPTION
**Pull request by cobra18t**

### CODE REVIEW

**Comment by jabdoa2** [comment]
Thanks for writing that up!

**Comment by cobra18t** [comment]
No problem. This is my first time contributing, so let me know if I still need to do anything on this or do something differently in the future.

**Comment by jabdoa2** [comment]
I got one request: Can you convert the images to jpg? They would be much smaller size wise. If possible try to keep the width at something < 800px. Otherwise the repo just becomes very large and the page would be rather slow (at least on mobile or older computers).

**Comment by cobra18t** [comment]
I updated the photos to a much smaller file size jpg.

**Pull request merged**
