### PR TITLE
Added description to organize modes in subfolders.

### PR DESCRIPTION
**Pull request by pmansukhani**

### CODE REVIEW

**Comment by jabdoa2** [comment]
Looks good. Thanks!

**Comment by jabdoa2** [comment]
One small thing: This needs to be against the dev branch. Latest = latest stable = 0.52. But I can just rebase this on merge.

**Comment by pmansukhani** [comment]
@jabdoa2 Would you like me to create a new PR against dev?

**Comment by jabdoa2** [comment]
Sorry I forgot to merge this. Will do it later today.

**Pull request merged**
