### PR TITLE
Updated player variable documentation

### PR DESCRIPTION
**Pull request by konjurertim**
I'll try to add more in the future.  I found this area of MPF to be very difficult to understand.  Hopefully, this will help others.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Thanks for writing this! You definitely need to add yourself to about/authors as well.

**Comment by konjurertim** [comment]
Do I have to close the pull request or is there another approval process before it is merged?

**Comment by jabdoa2** [comment]
I'm currently sailing. Will merge it later this week when I get home

**Comment by konjurer** [comment]
How's the sailing going?  Just checking to see if you are back and can check this in.

:)

Tim

**Comment by jabdoa2** [comment]
Oh sorry. I forgot. Thanks @q-dog

**Pull request merged**
