### PR TITLE
Add start_running option to show_player config

### PR DESCRIPTION
**Pull request by avanwinkle**
This PR adds documentation for the show_player `start_running` config option (https://github.com/missionpinball/mpf/pull/1524)

### CODE REVIEW

**Comment by avanwinkle** [comment]
Also, since I had some time today, I created a new recipe for rollover lanes and lane completion.

**Comment by jabdoa2** [comment]
Awesome!

**Comment by avanwinkle** [comment]
Updated with virtual environment instructions for windows, verified on my Windows 10 machine with a fresh install.

**Comment by jabdoa2** [comment]
`/home/travis/build/missionpinball/mpf-docs/cookbook/rollover_lanes_with_lane_change.rst:document isn't included in any toctree`

**Comment by avanwinkle** [comment]
Adding an update to Carousel documentation suggesting the use of *flipper_inactive* events instead of *flipper_active*

**Comment by avanwinkle** [comment]
@jabdoa2 I don't have write access to the repo, so the merge is up to you 😄

**Comment by jabdoa2** [comment]
> @jabdoa2 I don't have write access to the repo, so the merge is up to you 😄

Can fix that. Give me a sec.

**Pull request merged**
