### PR TITLE
Add some missing mech images

### PR DESCRIPTION
**Pull request by kevinleedrum**
This PR adds several missing mech photos (all taken by me), and also adds mention of #906 bulbs to the flasher page.

### CODE REVIEW

**Comment by jabdoa2** [comment]
Did you take all the pictures yourself? Are you ok to contribute them under creative commons license?

**Comment by kevinleedrum** [comment]
Yes, I took the photos today specifically for the docs. I am good with the license.

**Comment by jabdoa2** [comment]
Awesome. I will generate the docs locally later to see if we have to acale the images down a bit or if this looks good already

**Comment by jabdoa2** [comment]
Great pictures. Thanks!

**Pull request merged**
