### PR TITLE
Update game_mode.rst

### PR DESCRIPTION
**Pull request by travisbmartin**
Added example of lighting top lanes to increase a multiplier

### CODE REVIEW

**Comment by travisbmartin** [comment]
I have no idea why this is failing.  If someone figures out what I am doing wrong give me a heads up.

**Comment by jabdoa2** [comment]
The build failure is not your fault. It's caused by an update in Sphinx (version 1.8.0). I will have a look at it later.

**Comment by travisbmartin** [comment]
Thanks, Jan.  This is all new to me.

**Comment by jabdoa2** [comment]
This should not fail and it also does not fail locally for me nor on readthedocs (which renders and serves the docs). The examples do not render for some reasons. Will figure that out later.

Thanks for the example :-). You do not have to (or better: should not) close the PR of you want to have it merged. Just leave it open and we will have a look/merge it.

**Comment by travisbmartin** [comment]
Ok. I'm still learning

**Pull request merged**
