### PR TITLE
Atummons high score vars

### PR DESCRIPTION
**Pull request by atummons**
Updated documents regarding the ability to add extra variables to high scores.  Handles updates to how to show on award slides, saving to the data file, and recalling for attract mode slides.

I think I have it setup so it will appear on nav, but if I missed that step, please let me know!

### CODE REVIEW

**Comment by toomanybrians** [comment]
This is awesome! I think we also need to add the new page into the `mkdocs.yml` in the root of the repo. That will add it to the left-side menu system.

This is one of the things that is not ideal yet. The `mkdocs.yml` sets the page tree location for the general site navigation, but if you also want a list of all the pages in a section, then you need to manually maintain that list too.

There are a few plugins for mkdocs which are supposed to do this automatically (like you just put the page links in a page and then the plugin will generate the site-wide nav structure), but those wouldn't work for us (I think they were all-or-nothing but we would need them only for certain folders)? Anyway there's probably a better way, maybe this is just a documentation instructions thing? So see if you can get that added, or I can add it when I'm back at my desk next week.

**Comment by atummons** [comment]
Sounds good. I couldn't find that. But the mkdocs are new to me. I can also get some documentation updated for future people contributing to docs (or maybe it is and I just never looked there).

**Comment by toomanybrians** [comment]
I just added the line to mkdocs.yml and then merged this in. Thanks!

**Comment by atummons** [comment]
Thanks, I was just getting around to it this morning.

**Pull request merged**
