### PR TITLE
Adds new how-to to the cookbook: dual launch devices

### PR DESCRIPTION
**Pull request by bghill**
Adds a new cookbook page. Demonstrates a super simple example of overwriting the default behavior of the game mode.

### CODE REVIEW

**Comment by jabdoa2** [comment]
@bghill are you still working on this?

**Comment by jabdoa2** [comment]
@bghill let me know if I can help in any way.

**Comment by bghill** [comment]
@jabdoa2 Sorry for disappearing. A bit of life got in the way. I'll wrap this up this week.

**Comment by jabdoa2** [comment]
Don't worry. We are not in a hurry!

**Comment by jabdoa2** [comment]
Merged manually. Also adjusted the code to prevent duplicate ejects.

**Pull request closed without merging**
